# Generated by Django 5.0.4 on 2024-04-20 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('ta_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=75)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=120)),
                ('course_code', models.IntegerField()),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_APP.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_APP.course')),
                ('ta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_APP.ta')),
            ],
        ),
        migrations.AddField(
            model_name='ta',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_APP.user'),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('supervisor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_APP.user')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_APP.user'),
        ),
    ]
